### ISSUE TITLE
API Change

### ISSUE THREAD

**Issue by shvaikalesh** [roperzh/buble-brunch#2]
Hello again!

I am Aleksey, Brunch maintainer. I would like to add this plugin to our plugins manifest and feature it in our docs (Getting Started section, as an alternative to `babel-brunch`).

However, we don't recommend including `brunch` in key of `plugins` like `plugins.bubleBrunch`: none of our plugins has that. Docs is not clear enough on this aspect and I will definitely change them today.

**Comment by roperzh** [comment]
Hello @shvaikalesh!

It's great to hear that! 😃 . Thanks for the PR and the suggestions.

I just released [v4.2.3](https://www.npmjs.com/package/brunch-buble) with this changes, let me know if there is anything else that I can do from my side!
