### ISSUE TITLE
Transfer ownership to the Brunch organization

### ISSUE THREAD

**Issue by roperzh** [roperzh/buble-brunch#5]
As discussed in https://github.com/roperzh/buble-brunch/pull/4#issuecomment-275239610 we are in the process of transferring the ownership of the repo to the Brunch org.

Per https://github.com/roperzh/buble-brunch/pull/4#issuecomment-275239610 we should do the following:

- [x] Merge PR.
- [x] Add @aMarCruz to this repo.
- [x] Transfer ownership to the Brunch org using GitHub repo settings.
- [x] Give permissions on NPM for @paulmillr.
- [x] Update package data (See #7)
- [x] Publish new version

However, I'm facing issues when transferring the ownership of the repo, see attached:

![screen shot 2017-01-26 at 12 55 50 pm](https://cloud.githubusercontent.com/assets/4419992/22338711/caaf012e-e3c6-11e6-9ab0-9e7a982ae901.png)

cc: @denysdovhan

**Comment by denysdovhan** [comment]
@roperzh sure, because we already have a fork of this repo. Just a moment, I'm gonna remove a fork.

**Comment by denysdovhan** [comment]
@roperzh done. Our fork has been deleted.

**Comment by roperzh** [comment]
@denysdovhan thank you! Unfortunately seems like I need permissions on the Brunch org to do that:

![screen shot 2017-01-26 at 2 13 07 pm](https://cloud.githubusercontent.com/assets/4419992/22342047/d5e18aca-e3d1-11e6-9db5-1681d1faf5e2.png)

However, while I was dealing with npm in order to give permissions to paulmillr, I realized that maybe this is not the repo that you are looking for... This repo is registered in npm as `brunch-buble` (check [here](https://github.com/roperzh/buble-brunch/blob/master/package.json#L2)). And seems like you are looking for [`buble-brunch`](https://www.npmjs.com/package/buble-brunch) which seems abandoned (that's why I started this repo).

I know, it sucks :S. If you still want to transfer this repo to the org, I'm happy to do that.

**Comment by denysdovhan** [comment]
@roperzh can you add me as a contributor to your repo?

**Comment by roperzh** [comment]
@denysdovhan done :)

![screen shot 2017-01-26 at 2 31 18 pm](https://cloud.githubusercontent.com/assets/4419992/22342736/24d1e704-e3d4-11e6-8d62-1fb4ecdea6e5.png)

**Comment by denysdovhan** [comment]
@roperzh got it, but I still don't have access to the Settings tab. Transfer ownership to me, I'll transfer it to Brunch  ¯\_(ツ)_/¯ 

> This repo is registered in npm as `brunch-buble`

Yeah, we're looking for `buble-brunch`, but it's okay, I'm gonna contact the owner of this package.

**Comment by roperzh** [comment]
> transfer ownership to me, I'll transfer it to Brunch ¯_(ツ)_/¯

@denysdovhan Done! :)

**Comment by denysdovhan** [comment]
Done. This repo is a part of Brunch org.

**Comment by roperzh** [comment]
Great! I'll look into transferring the npm ownership today.

**Comment by denysdovhan** [comment]
>  This repo is registered in npm as `brunch-buble` (check [here](https://github.com/roperzh/buble-brunch/blob/master/package.json#L2)). And seems like you are looking for [`buble-brunch`](https://www.npmjs.com/package/buble-brunch) which seems abandoned (that's why I started this repo).

Hi, @joelanglois, could you help us here? Please give NPM ownership for `buble-brunch` to @paulmillr.

**Comment by aMarCruz** [comment]
@roperzh , @denysdovhan , I have this problem to accept your invitation:

![image](https://cloud.githubusercontent.com/assets/6636980/22355554/df6cb168-e3f0-11e6-8e6d-892ba8231c51.png)

Regarding "buble-brunch" in npm this is the email in the profile: joe.desruisseaux.langlois@gmail.com
He could not transfer the property because he deleted his repository, so the process should be done by email at npm explaining the situation.

npm rules in https://docs.npmjs.com/policies/disputes

**Comment by denysdovhan** [comment]
@aMarCruz I've lost my permissions for this repo, because I've transfered it to the other teams in Brunch org. Gonna add you as a contributor as soon as @paulmillr give me access to these teams.

**Comment by JoeLanglois** [comment]
Hmmm, not sure what I can do for you guys, I deleted the repo

**Comment by denysdovhan** [comment]
@JoeLanglois you should give us permissions to your package on npm. Add @paulmillr, please.

**Comment by roperzh** [comment]
@JoeLanglois if you are wondering how to do it, you just need to add a new npm owner, as described in the [doc](https://docs.npmjs.com/cli/owner)

```bash
$ npm owner add paulmillr
```
---

@denysdovhan access for paulmillr to `brunch-buble` on npm granted :).

**Comment by JoeLanglois** [comment]
I don't have the local git repository anymore, how can I do this?


2017-01-30 7:53 GMT-05:00 Roberto Dip <notifications@github.com>:

**Comment by JoeLanglois** [comment]
It's done, paulmillr should have access to the repo


2017-01-30 14:22 GMT-05:00 Joé Langlois <joe.desruisseaux.langlois@gmail.com

**Comment by denysdovhan** [comment]
Gonna open a PR, with update of `package.js` data.

**UPD:** #7

**Comment by paulmillr** [comment]
@amarcruz can you execute the command?

```bash
npm deprecate bublejs-brunch "bublejs-brunch is unsupported, use buble-brunch instead"
```

**Comment by aMarCruz** [comment]
@paulmillr , Done!
